---
name: CGI-Application-Plugin-ErrorPage
version: 1.12
author: []
abstract: A simple error page plugin for CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Application: 0
  Params::Validate: 0
  Test::More: 0
provides:
  CGI::Application::Plugin::ErrorPage:
    file: lib/CGI/Application/Plugin/ErrorPage.pm
    version: 1.12
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
